### ISSUE TITLE
can I include the Creative AI meetup on this event? 

### ISSUE THREAD

**Issue by silky** [bendechrai/mumumelb#2]
i organise this - https://www.meetup.com/preview/Melbourne-Creative-AI-Meetup

i'd be keen to hook into this event for anyone from our meetup that'd be keen to come along

thoughts?

**Comment by bendechrai** [comment]
Yes. Please do!

**Comment by bendechrai** [comment]
Did you want to submit a PR, or get me to add you in?

**Comment by silky** [comment]
ah i can't see how to run the website locally so i don't want to do a PR because i'll probably break something

i'll get you a logo shortly

**Comment by silky** [comment]
![image](https://user-images.githubusercontent.com/129525/32083046-8d001846-bb0b-11e7-9919-cc0a38652e94.png)

**Comment by bendechrai** [comment]
That logo is going to look really obscure in a 100x100 pixel container. Can I just take this bit:

![image](https://user-images.githubusercontent.com/76757/32083076-cbae8ef6-bb0b-11e7-85a7-0eb1ba7a538f.png)

**Comment by silky** [comment]
haha, yeah, definitely :)

**Comment by silky** [comment]
thanks!

**Comment by bendechrai** [comment]
Done, pushed, should be deployed to prod soon. Thanks for joining us. Don't forget to follow twitter.com/mumumelb for updates :)
